### ISSUE TITLE
Build on RHEL 8.7 always fail

### ISSUE THREAD

**Issue by Lathanderjk** [Castaglia/proftpd-mod_geoip2#7]
I try to build this module on RHEL 8.7 as built-in,shared or DSO but always with same outcom:
```
mod_geoip2.c: In function 'get_geoip_data_text':
mod_geoip2.c:672:7: error: implicit declaration of function 'pr_snprintf'; did you mean 'vsnprintf'? [-Werror=implicit-function-declaration]
       pr_snprintf(buf, sizeof(buf)-1, "%lu", (unsigned long) entry_data.uint32);
       ^~~~~~~~~~~
       vsnprintf
cc1: some warnings being treated as errors
make[1]: *** [Makefile:31: mod_geoip2.o] Error 1
```

**Comment by Castaglia** [comment]
Which version of ProFTPD are you using?

**Comment by Lathanderjk** [comment]
Proftpd version 1.3.6e

**Comment by Castaglia** [comment]
Thanks.  The `pr_snprintf()` function was added in ProFTPD 1.3.7, for https://github.com/proftpd/proftpd/issues/260.  I'll what I can do, to add a workaround to this module.

**Comment by Castaglia** [comment]
@Lathanderjk This should now be fixed in master.  Thanks for reporting this issue!
